# Exercício:

## 01 – Obtenha os resultados e retorne o código em Python dos seguintes cálculos:

a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [3]:
a = 2.0 + 3.0 / 5.0
print(f'Valor de a: {a}')
b = (a + 10.2) - 5.0 * 2.0
print(f'Valor de b: {b}')
c = a / b + 33.8
print(f'Valor de c: {c}')
d = a / (b + c)
print(f'Valor de d: {d}')
e = d * 2
print(f'Valor de e: {e}')

Valor de a: 2.6
Valor de b: 2.799999999999999
Valor de c: 34.72857142857143
Valor de d: 0.0692805481537876
Valor de e: 0.1385610963075752


## 02 – Obtenha os resultados e retorne o código em Python dos seguintes cálculos:

a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [4]:
lista_a = [2.0, 3.0, 5.0] + [10, 20, 30]
print(f'Valor de lista_a: {lista_a}')
lista_b = lista_a * 2
print(f'Valor de lista_b: {lista_b}')
lista_c = lista_a + lista_b
print(f'Valor de lista_c: {lista_c}')
lista_d = lista_a / (lista_b + lista_c)
print(f'Valor de lista_d: {lista_d}')

Valor de lista_a: [2.0, 3.0, 5.0, 10, 20, 30]
Valor de lista_b: [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]
Valor de lista_c: [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]


TypeError: unsupported operand type(s) for /: 'list' and 'list'

## 03 – Usando os objetos simples obtidos no exercício 01, instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [7]:
import math
lista_ex_1 = [a, b, c, d, e]
raiz_quadrada = [math.sqrt(x) for x in lista_ex_1]
lista_final = lista_ex_1 + raiz_quadrada
print(f'Raiz quadrada da lista ex 1: {raiz_quadrada}')
print(f'Lista final: {lista_final}')

Raiz quadrada da lista ex 1: [1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501]
Lista final: [2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752, 1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501]


## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [8]:
import numpy as np
lista_duplicada = lista_final * 2
np_array = np.array(lista_duplicada).reshape(5, 4)
print(f'Array numpy: \n{np_array}')

Array numpy: 
[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   1.61245155  1.67332005  5.89309523]
 [ 0.26321198  0.37223796  2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   1.61245155]
 [ 1.67332005  5.89309523  0.26321198  0.37223796]]


## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [56]:
medias_colunas = np.mean(np_array, axis=0)

# Converter para lista
lista_medias = medias_colunas.tolist()

print("Médias de cada coluna:", lista_medias)

Médias de cada coluna: [7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]


## 06 – O atributo shape pertence ao escopo dos objetos de classe numpy array. Ela retorna uma tupla onde o primeiro valor é o número de linhas e o segundo valor o de colunas contidas no array. Usando a informação do número total de valores presentes no numpy array do exercício 4 insira neste array a lista obtida no exercício 5. Recupere o array.
Obs.:  Atributos não usam () na chamada.

In [62]:
print(f'Shape do array numpy: {np_array.shape}')
print(f'Lista medias: {lista_medias}')
array_expandido = np.insert(np_array, len(lista_medias)+1, lista_medias, axis=0)
array_expandido
print(array_expandido.shape)



Shape do array numpy: (5, 4)
Lista medias: [7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]
(6, 4)


## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [81]:
import pandas as pd
reshape_exp = array_expandido.reshape(6, 4)
pd_reshaped = pd.DataFrame(reshape_exp.copy())
rounded_df = pd_reshaped.round(3)
print(f'DataFrame arredondado: \n{rounded_df}')



DataFrame arredondado: 
        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [82]:
medias_linhas = rounded_df.mean(1)
medias_linhas
rounded_df["media_linha"] = medias_linhas
print(f'DataFrame com média das linhas: \n{rounded_df}')

DataFrame com média das linhas: 
        0      1       2      3  media_linha
0   2.600  2.800  34.729  0.069     10.04950
1   0.139  1.612   1.673  5.893      2.32925
2   0.263  0.372   2.600  2.800      1.50875
3  34.729  0.069   0.139  1.612      9.13725
4   1.673  5.893   0.263  0.372      2.05025
5   7.881  2.149   7.881  2.149      5.01500


C:\Users\paulo\AppData\Local\Temp\ipykernel_11544\834730521.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  medias_linhas = rounded_df.mean(1)


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [83]:
column_describe = rounded_df.describe()
print(column_describe)
print('============================================')
row_describe = rounded_df.transpose().describe()
print(row_describe)

               0         1          2         3  media_linha
count   6.000000  6.000000   6.000000  6.000000     6.000000
mean    7.880833  2.149167   7.880833  2.149167     5.015000
std    13.455228  2.107787  13.455228  2.107787     3.758615
min     0.139000  0.069000   0.139000  0.069000     1.508750
25%     0.615500  0.682000   0.615500  0.682000     2.120000
50%     2.136500  1.880500   2.136500  1.880500     3.672125
75%     6.560750  2.637250   6.560750  2.637250     8.106688
max    34.729000  5.893000  34.729000  5.893000    10.049500
               0         1         2          3        4      5
count   5.000000  5.000000  5.000000   5.000000  5.00000  5.000
mean   10.049500  2.329250  1.508750   9.137250  2.05025  5.015
std    14.289318  2.147244  1.193969  14.788245  2.28691  2.866
min     0.069000  0.139000  0.263000   0.069000  0.26300  2.149
25%     2.600000  1.612000  0.372000   0.139000  0.37200  2.149
50%     2.800000  1.673000  1.508750   1.612000  1.67300  5.015
75%

com o metodo describe foi possivel chegar nas mesmas médias de linhas e colunas bem interessante.

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [ ]:
custom_rows = ['line_1', 'line_2', 'line_3', 'line_4', 'line_5', 'media_colunas']
transposed_df = rounded_df.transpose()
transposed_df.columns = custom_rows
transposed_df
custom_columns = ['col_1', 'col_2', 'col_3', 'col_4', 'media_linha']
back_to_original = transposed_df.transpose()
back_to_original.columns = custom_columns
print(f'DataFrame final: \n{back_to_original}')

,line_1,line_2,line_3,line_4,line_5,media_colunas
0,2.6000,0.13900,0.26300,34.72900,1.67300,7.881
1,2.8000,1.61200,0.37200,0.06900,5.89300,2.149
2,34.7290,1.67300,2.60000,0.13900,0.26300,7.881
3,0.0690,5.89300,2.80000,1.61200,0.37200,2.149
media_linha,10.0495,2.32925,1.50875,9.13725,2.05025,5.015
